trigger:
- master
- develop

variables:
  BuildConfiguration: 'release'
  Projects: '**/*.csproj;!*/Console.Runner.csproj'
  TestsProjects: '**/*.Tests.csproj'
  PackProjects: '**/*.csproj;!**/*.Tests.csproj;!*/Console.Runner.csproj'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitVersion@5
  displayName: GitVersion
  inputs:
    runtime: 'core'
    preferBundledVersion: false
    configFilePath: '$(Build.SourcesDirectory)/GitVersion.yml'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    projects: '$(Projects)'
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: '$(TestsProjects)'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\TestResults\Coverage\coverage.cobertura.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)\TestResults\Coverage\coverage.*.xml'

- task: DotNetCoreCLI@2
  displayName: 'Package NuGet'
  inputs:
    command: 'pack'
    packagesToPack: '$(PackProjects)'
    nobuild: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.NuGetVersion'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'
